#!/usr/bin/perl

use lib qw(/usr/lib/libDrakX);
use common;
use Xconfig::xfree;
use Xconfig::resolution_and_depth;

require_root_capability();

my $resolution = eval { Xconfig::xfree->read->get_resolution };
Xconfig::resolution_and_depth::set_default_background($resolution);